[package]
edition = "2021"
name = "ltsv"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
std = []

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
features = ["std"]
